removing unnecessary sudo for check
quoting from https://www.kernel.org/doc/Documentation/vm/ksm.txt
> The KSM daemon is controlled by sysfs files in /sys/kernel/mm/ksm/,
> readable by all but writable only by root

additionally:
* lower script dependencies down to use any /bin/sh, as
  there are no special needs for BASH
* kill the "useseless use of cat" and replace by shell built-ins

diff --git a/debs/zabbix-check/zabbix-check-ksm/usr/sbin/zabbix_check_ksm b/debs/zabbix-check/zabbix-check-ksm/usr/sbin/zabbix_check_ksm
--- a/debs/zabbix-check/zabbix-check-ksm/usr/sbin/zabbix_check_ksm
+++ b/debs/zabbix-check/zabbix-check-ksm/usr/sbin/zabbix_check_ksm
@@ -1,7 +1,13 @@
-#!/bin/bash
+#!/bin/sh
 
-value=$1
+fail_ () {
+	echo "ZBX_NOTSUPPORTED"
+	exit 1
+}
 
-cat /sys/kernel/mm/ksm/$value 2> /dev/null || echo "ZBX_NOTSUPPORTED"
+[ $# -eq 1 ] || fail_
+[ -d /sys/kernel/mm/ksm ] || fail_
+
+read value 2>/dev/null </sys/kernel/mm/ksm/$1 && printf $value || fail_
 
 exit 0
