zabbix-check-dpkg: formatting and documentation

diff --git a/debs/zabbix-check/zabbix-check-dpkg/debian/postrm b/debs/zabbix-check/zabbix-check-dpkg/debian/postrm
--- a/debs/zabbix-check/zabbix-check-dpkg/debian/postrm
+++ b/debs/zabbix-check/zabbix-check-dpkg/debian/postrm
@@ -1,21 +1,45 @@
 #!/bin/sh
+# postrm script for zabbix-check-dpkg
+#
+# see: dh_installdeb(1)
 
 set -e
 
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 case "$1" in
+
     remove|purge)
-
         rm -rf /usr/share/zabbix/dpkg || true
-
-    ;;
+        if which invoke-rc.d >/dev/null 2>&1; then
+            invoke-rc.d zabbix-agent stop || true
+            invoke-rc.d zabbix-agent start || true
+        else
+            /etc/init.d/zabbix-agent stop || true
+            /etc/init.d/zabbix-agent start || true
+        fi        
+        ;;
 
     failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
-    ;;
+        ;;
 
     *)
         echo "postrm called with unknown argument \`$1'" >&2
         exit 1
 esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
